services:
  gitea-repo-backup:
    build:
      context: .
      image: gitea-repo-backup:latest
    container_name: gitea-repo-backup
    restart: unless-stopped
    environment:
      - GITEA_API_KEY=${GITEA_API_KEY}
      - GITEA_PUBLIC_API_KEY=${GITEA_PUBLIC_API_KEY}
    volumes:
      - ./config.yml:/app/config.yml:ro
