services:
  gitea-repo-backup:
    build:
      context: .
    image: gitea-repo-backup:latest
    container_name: gitea-repo-backup
    restart: unless-stopped
    volumes:
      - ./config.yml:/app/config.yml:ro
      - ./.env:/app/.env:ro
      - ./backups:/app/backups
