gitea:
  git:
    url: git.ethanmt.com
    api-key: ${GITEA_API_KEY}
    folder-name: gitea
    schedule: "* * * * *"

  git-public:
    url: git-public.ethanmt.com
    api-key: ${GITEA_PUBLIC_API_KEY}
    folder-name: gitea-public
    schedule: "* * * * *"