gitea:
  git:
    url: https://git.ethanmt.com
    api-key: ${GITEA_API_KEY}
    folder-name: git
    schedule: "0 0 * * *"

  git-public:
    url: https://git-public.ethanmt.com
    api-key: ${GITEA_PUBLIC_API_KEY}
    folder-name: git-public
    schedule: "0 0 * * *"